import type {Metadata} from 'next';
import localFont from 'next/font/local';
import './globals.css';
import {ReactNode} from 'react';
import {UIConst} from '@/shared';

const pretendard = localFont({
  src: './woff2/PretendardVariable.woff2',
  display: 'swap',
  preload: true,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

declare global {
  interface Window {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    KaKao: any;
  }
}

function MobileContainer({children}: Readonly<{children: ReactNode}>) {
  return (
    <div
      style={{
        maxWidth: UIConst.mobileContainerSize.width,
        minHeight: '100vh',
        marginLeft: 'auto',
        marginRight: 'auto',
        backgroundColor: 'white',
        position: 'relative',
      }}
    >
      {children}
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        <MobileContainer>{children}</MobileContainer>
      </body>
    </html>
  );
}
